[project]
name = 'SIP_Impl'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.nft-trait-v2]
path = 'contracts/nft-trait.clar'
clarity_version = 2
epoch = '2.1'

[contracts.SIP_Impl-v2]
path = 'contracts/SIP_Impl.clar'
clarity_version = 2
epoch = '2.1'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
